version: "2"
run:
  modules-download-mode: readonly
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - gosec
    - misspell
    - revive
    - unconvert
    - gocritic
    - perfsprint
    - sloglint
    - ineffassign
    - unused
    - prealloc
    - staticcheck
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      settings:
        rangeValCopy:
          sizeThreshold: 32
        hugeParam:
          sizeThreshold: 300  # Increased from 80 to 300 bytes to avoid noise from slog.Record (288 bytes)
    perfsprint:
      int-conversion: true
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: true
    revive:
      severity: warning
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
          severity: warning
          disabled: true
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/wukong0111/go-banks
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
